#pragma once
#include <stdint.h>
int klin_ble_init(void);
int klin_ble_advertise(const char *name);
int klin_ble_stop_advertise(void);
int klin_ble_connected(void);
int klin_ble_advertising(void);
int klin_ble_wait_connected(int timeout_ms);
int klin_ble_stop(void);
int klin_ble_gatt_set(const uint8_t *data, int len);
int klin_ble_gatt_get(uint8_t *out, int max_len);
int klin_ble_gatt_len(void);
int klin_ble_gatt_notify(void);
int klin_ble_gatt_written(void);
int klin_ble_scan_start(int duration_ms);
int klin_ble_scan_stop(void);
int klin_ble_scan_count(void);
int klin_ble_scan_rssi(int index);
int klin_ble_scan_addr_type(int index);
int klin_ble_scan_addr(int index, uint8_t *out6);
int klin_ble_scan_name(int index, uint8_t *out, int max_len);
int klin_ble_central_connect(int index, int timeout_ms);
int klin_ble_central_connected(void);
int klin_ble_central_wait_connected(int timeout_ms);
int klin_ble_central_disconnect(void);
int klin_ble_gattc_discover(int timeout_ms);
int klin_ble_gattc_ready(void);
int klin_ble_gattc_read(int timeout_ms);
int klin_ble_gattc_write(const uint8_t *data, int len, int timeout_ms);
int klin_ble_gattc_subscribe(int timeout_ms);
int klin_ble_gattc_notified(void);
int klin_ble_gattc_get(uint8_t *out, int max_len);
int klin_ble_gattc_len(void);
