#pragma once
#include <stdint.h>
int klin_ble_init(void);
int klin_ble_gatt_uuid16(int svc_uuid16, int chr_uuid16);
int klin_ble_gatt_uuid128(const uint8_t *svc16, const uint8_t *chr16);
int klin_ble_gatt_add_uuid16(int svc_uuid16, int chr_uuid16);
int klin_ble_gatt_add_uuid128(const uint8_t *svc16, const uint8_t *chr16);
int klin_ble_gatt_clear(void);
int klin_ble_gatt_svc_count(void);
int klin_ble_gatt_svc_uuid16(void);
int klin_ble_gatt_chr_uuid16(void);
int klin_ble_advertise(const char *name);
int klin_ble_stop_advertise(void);
int klin_ble_connected(void);
int klin_ble_advertising(void);
int klin_ble_wait_connected(int timeout_ms);
int klin_ble_stop(void);
int klin_ble_gatt_set(const uint8_t *data, int len);
int klin_ble_gatt_set_at(int index, const uint8_t *data, int len);
int klin_ble_gatt_get(uint8_t *out, int max_len);
int klin_ble_gatt_get_at(int index, uint8_t *out, int max_len);
int klin_ble_gatt_len(void);
int klin_ble_gatt_len_at(int index);
int klin_ble_gatt_notify(void);
int klin_ble_gatt_notify_at(int index);
int klin_ble_gatt_written(void);
int klin_ble_gatt_written_at(int index);
int klin_ble_scan_start(int duration_ms);
int klin_ble_scan_stop(void);
int klin_ble_scan_count(void);
int klin_ble_scan_rssi(int index);
int klin_ble_scan_addr_type(int index);
int klin_ble_scan_addr(int index, uint8_t *out6);
int klin_ble_scan_name(int index, uint8_t *out, int max_len);
int klin_ble_central_connect(int index, int timeout_ms);
int klin_ble_central_connected(void);
int klin_ble_central_wait_connected(int timeout_ms);
int klin_ble_central_disconnect(void);
int klin_ble_gattc_select(int index);
int klin_ble_gattc_uuid16(int svc_uuid16, int chr_uuid16);
int klin_ble_gattc_uuid128(const uint8_t *svc16, const uint8_t *chr16);
int klin_ble_gattc_discover(int timeout_ms);
int klin_ble_gattc_ready(void);
int klin_ble_gattc_read(int timeout_ms);
int klin_ble_gattc_write(const uint8_t *data, int len, int timeout_ms);
int klin_ble_gattc_subscribe(int timeout_ms);
int klin_ble_gattc_notified(void);
int klin_ble_gattc_get(uint8_t *out, int max_len);
int klin_ble_gattc_len(void);
int klin_ble_bond_enable(void);
int klin_ble_bond_passkey(int passkey);
int klin_ble_passkey(void);
int klin_ble_passkey_action(void);
int klin_ble_passkey_inject(int passkey);
int klin_ble_bond_start(void);
int klin_ble_bonded(void);
int klin_ble_wait_bonded(int timeout_ms);
int klin_ble_bond_count(void);
int klin_ble_bond_clear(void);
int klin_ble_privacy_enable(void);
int klin_ble_privacy_disable(void);
int klin_ble_privacy_enabled(void);
int klin_ble_own_addr_type(void);
int klin_ble_own_addr(uint8_t *out6);
int klin_ble_mesh_enable(void);
int klin_ble_mesh_enabled(void);
int klin_ble_mesh_provisioned(void);
int klin_ble_mesh_primary_addr(void);
int klin_ble_mesh_onoff(void);
int klin_ble_mesh_onoff_set(int onoff);
int klin_ble_mesh_onoff_changed(void);
int klin_ble_mesh_oob_number(void);
int klin_ble_mesh_reset(void);
